server:
  port: 8081
  servlet:
    context-path: /stocksapp
spring:
  application:
    name: stocks-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: stockadmin
    password: stockadmin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/